import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ChakraProvider } from '@chakra-ui/react'
import EmailFunction from "@/context/EmailContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Advert Monk - Media Company",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ChakraProvider>
        <Header/>
        <EmailFunction>
      <main className="relative flex flex-col min-h-screen">
          <div className="flex-grow flex-1">{children}</div>
        </main>
        </EmailFunction>
        <Footer/>
        </ChakraProvider>
      </body>
    </html>
  );
}
